<?php

namespace Ankitgupta\Payments;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Config;

class PaymentsController extends Controller
{
    public function pay() {
        $amount = 70.00;

        //................................................
        //payment config defined in PaymentServiceProvider
        //................................................

        $login = config('payment-config.LOGIN'); //login ID of merchant
        $pass = config('payment-config.PASS'); //merchant password
        $productid = 'NSE'; //product ID
        $txnid = rand(100000,999999); // Merchant’s Transaction ID (Unique Transaction ID generated by the Merchant)
        $currency = 'INR';
        $transactionType = 'NBFundTransfer';
        $serviceCharge = '0'; //  Charged by the merchant
        $clientCode = 'dummy'; // customer identification from merchant side
        $customerAccount = '12345678';
        date_default_timezone_set("Asia/Kolkata");
        $date = date('d/m/Y').'%20'.date('H:i:s');
        $signature_string = $login.$pass.$transactionType.$productid.$txnid.$amount.$currency;
        $signature = hash_hmac('sha512', $signature_string, 'KEY123657234');

        $url = 'https://paynetzuat.atomtech.in/paynetz/epi/fts?login='.$login.'&pass='.$pass.'&prodid='.$productid.'&txnid='.$txnid.'&amt='.$amount.'&txncurr='.$currency.'&ttype='.$transactionType.'&clientcode='.$clientCode.'&date='.$date.'&txnscamt='.$serviceCharge.'&custacc='.$customerAccount.'&signature='.$signature.'&ru=http://127.0.0.1:8000/pay-response';

        $client = new \GuzzleHttp\Client();
        $res = $client->get($url);
        echo $res->getBody();
    }

    public function payResponse() {
        dd(request());
    }
}
